### ISSUE TITLE
Bug: highlighting across paragraphs breaks

### ISSUE THREAD

**Issue by moltar** [funktechno/texthighlighter#123]
This issue is:

- [x] Bug report
- [ ] Feature request
- [ ] Improvement

### Actual behaviour

Highlighting across paragraphs breaks.

### Expected behaviour

Should not break.

### Steps to reproduce

1. Highlight text across 2 or more paragraphs (blocks)
2. Change color
3. Hihglight text across the same 2 paragraphs but a sub section of the text that is highlighted already
4. Observe some text shifting

### Screenshots

![screenshot-20210601T110226-5uTMqerN](https://user-images.githubusercontent.com/491247/120264876-f08dba80-c2c8-11eb-9964-f69e58d356de.gif)

### Logs 

N/A

### Configuration

- OS: macOS
- Browser: Firefox
- Browser version: 88

**Comment by sinderpl** [comment]
Tried to fix it atleast on a  basic level , might need more cleanup, hope this helps :)

**Comment by lastlink** [comment]
@moltar @sinderpl, merged and released.
