### ISSUE TITLE
ts-node does not need to be a dependency

### ISSUE THREAD

**Issue by moltar** [funktechno/texthighlighter#150]
This issue is:

- [x] Bug report
- [ ] Feature request
- [ ] Improvement

### Actual behaviour

`ts-node` is listed as a dep

### Expected behaviour

Should be a `devDep`

### Steps to reproduce

Look at `package.json` file.

### Screenshots

N/A

### Logs 

N/A

### Configuration

N/A

**Comment by lastlink** [comment]
@moltar prs are welcome
