### ISSUE TITLE
Text not being highlighted inside an Iframe

### ISSUE THREAD

**Issue by bozzmob** [funktechno/texthighlighter#42]
This issue is:

- [x] Bug report
- [ ] Feature request
- [ ] Improvement

### Actual behaviour
Text not being highlighted inside an Iframe

### Expected behaviour
Text should be being highlighted inside an Iframe as well?

### Steps to reproduce
Please try iframe demo from the README

### Logs 
* attach export from options screen. Can replace urls and repo names used.

### Configuration

- OS: Windows10
- Browser: Brave(Chromium)
- Browser version: Chromium 86

**Comment by lastlink** [comment]
I'm aware of this issue, I might need to remove it from the reader demo. Iframes are hard to work with. Thanks!

**Comment by lastlink** [comment]
Should be an issue with the demo not the library.
