### ISSUE TITLE
Support for overlapping highlights

### ISSUE THREAD

**Issue by brfrth** [funktechno/texthighlighter#7]
I'm currently attempting to use this library. Here is the workflow I have.

1. On text selection, highlight the text and give it a class of `selection`. This is triggered on mouseup.

```js
methods: {
  runSelect() {
    const options = {
      color: false,
      highlightedClass: "selected",
      onAfterHighlight: (range, highlights, timestamp) => {
        // Finds the specific highlight for this selection (by timestamp)
        this.currentHighlight = this.findHighlight(timestamp);
        if (this.currentHighlight) {
          this.modal = true;
        }
      },
    };
    doHighlight(this.$refs.content, false, options);
  }
}
```

2. Open a modal to enter a comment
3. Once submitted, the comment and the selection (serialized) are stored. While doing this I change the class in the JSON to highlight from selected to keep highlights and selections separate.
4. After closing the modal, all highlights with class `selection` are cleared

```js
removeHighlights(this.$refs.content, {
  highlightedClass: 'selected'
})
```

5. All the highlight objects are loaded from the database and parsed to JSON. They are then deserialized. **Everything works great up to here. Highlights are stored properly and reload just fine.**

Here is the issue though. When I now try to select anything that is already highlighted, my modal does not even open. If any part of the selection overlaps with an existing highlight the existing highlight is simply extended. This means that when I have two words selected in the text and select the whole text it all gets wrapped in an element with a class of `highlight` without ever creating a new highlight. It just modifies an existing one. So it's not even doing what's defined in `runSelect()` as it does not create a new element with class `selection`. I presume there is merging going on.

Is there a way to solve this? I would prefer if it would override existing highlights instead of expanding them.

**Comment by lastlink** [comment]
Comments will not work well with this current implementation of highlighting. This auto merges highlights and will cause conflicts if you are allowing comments with highlights. B/c this allows you to be specific with how much to highlight and auto merged it won't work great. If you triggered highlights off of whole elements such as every paragraph highlights would work better. If you wanted to still use this and comments you might have to check the serialized object before and after and readd the comments. This won't deserialize your comments.

**Comment by brfrth** [comment]
Yeah it’s a bit unfortunate. Sadly it seems that text highlighting with JavaScript has basically no libraries. After lots of trying this one worked best for me.

**Comment by brfrth** [comment]
Closing this then :)

**Comment by lastlink** [comment]
@brfrth you are welcome to add prs to this repo to add support for different types. I just don't really have bandwidth for this now and the current setup is working for me. I'd like to eventually bring over the unit tests and an automated github actions pipeline to verify.
